import { collection, addDoc, updateDoc, deleteDoc, doc, onSnapshot, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
import { getFirebaseDb } from './firebase-config.js';
import { subscribeAuth } from './auth.js';
const $=id=>document.getElementById(id);const ADMIN_EMAIL='mohamedishankunnummal@gmail.com';
let admin=false,user=null,cache=[],editingId=null,stop=null;
function text(parent,tag,value,cls){const e=document.createElement(tag);if(cls)e.className=cls;e.textContent=value??'';parent.appendChild(e);return e;}
function row(task){const r=document.createElement('div');r.className='task-row';text(r,'span',task.type==='homework'?'Homework':'Announcement',`task-tag ${task.type==='homework'?'homework':'announcement'}`);const body=document.createElement('div');body.className='task-body';text(body,'p',task.subject,'task-subject');text(body,'p',task.detail,'task-detail');r.appendChild(body);text(r,'span',task.due,'task-due');const acts=document.createElement('div');acts.className='task-admin-actions admin-only';acts.hidden=!admin;const ed=document.createElement('button');ed.className='task-icon-btn';ed.type='button';ed.textContent='✎';ed.setAttribute('aria-label','Edit task');ed.onclick=()=>openForm(task);const del=document.createElement('button');del.className='task-icon-btn';del.type='button';del.textContent='✕';del.setAttribute('aria-label','Delete task');del.onclick=()=>removeTask(task.id);acts.append(ed,del);r.appendChild(acts);return r;}
function render(){const list=$('taskList');if(!list)return;list.replaceChildren();if(!user){text(list,'p','Sign in to view the live class task list.','task-empty');return;}if(!cache.length){text(list,'p','Nothing logged for today.','task-empty');return;}cache.forEach(t=>list.appendChild(row(t)));}
async function listen(){if(stop||!user)return;try{const db=await getFirebaseDb();stop=onSnapshot(collection(db,'tasks'),snap=>{cache=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.createdAt?.seconds||0)-(b.createdAt?.seconds||0));render();},err=>{console.error(err);cache=[];const list=$('taskList');if(list)list.innerHTML='<p class="task-empty">Couldn\'t load tasks right now. Try again in a moment.</p>';});}catch(err){console.error(err);const list=$('taskList');if(list)list.innerHTML='<p class="task-empty">Live tasks are temporarily unavailable.</p>';}}
function stopListen(){stop?.();stop=null;cache=[];}
function visibility(){document.querySelectorAll('.admin-only').forEach(e=>e.hidden=!admin);if($('addTaskBtn'))$('addTaskBtn').hidden=!admin;}
function openForm(task=null){if(!admin)return;const f=$('taskForm');if(!f)return;editingId=task?.id||null;f.elements.subject.value=task?.subject||'';f.elements.type.value=task?.type||'homework';f.elements.detail.value=task?.detail||'';f.elements.due.value=task?.due||'';f.hidden=false;f.querySelector('button[type="submit"]').textContent=editingId?'Save changes':'Add task';f.elements.subject.focus();}
function closeForm(){const f=$('taskForm');if(!f)return;f.reset();f.hidden=true;editingId=null;}
async function removeTask(id){if(!admin||!user)return;const target=cache.find(t=>t.id===id);if(!confirm(`Delete "${target?.subject||'this task'}"?`))return;try{const db=await getFirebaseDb();await deleteDoc(doc(db,'tasks',id));}catch(e){console.error(e);alert('Couldn\'t delete that task. Check the Firebase admin permissions.');}}
async function submit(e){e.preventDefault();if(!admin||!user)return;const f=e.currentTarget;const data={subject:f.elements.subject.value.trim(),type:f.elements.type.value,detail:f.elements.detail.value.trim(),due:f.elements.due.value.trim()};if(!data.subject||!data.detail||!data.due)return alert('Fill in the subject, details, and due field.');try{const db=await getFirebaseDb();if(editingId)await updateDoc(doc(db,'tasks',editingId),data);else await addDoc(collection(db,'tasks'),{...data,createdAt:serverTimestamp()});closeForm();}catch(e){console.error(e);alert('Couldn\'t save that task. Check the Firebase admin permissions.');}}
export function initTasks(){const f=$('taskForm');$('addTaskBtn')?.addEventListener('click',()=>openForm());f?.addEventListener('submit',submit);f?.querySelector('[data-action="cancel"]')?.addEventListener('click',closeForm);const date=$('todayDate');if(date)date.textContent=`${new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})} — homework, tasks, and announcements, kept current.`;subscribeAuth(state=>{user=state.user;admin=!!state.admin||(state.user?.email||'').trim().toLowerCase()===ADMIN_EMAIL;visibility();if(user){if($('todayNote'))$('todayNote').textContent=admin?'You have admin controls for this class task board.':'Live class tasks and announcements.';listen();}else{stopListen();closeForm();if($('todayNote'))$('todayNote').textContent='Sign in to see the live class task list.';}render();});}
